package Persistencias;
// Generated 31 ene 2024 10:59:50 by Hibernate Tools 5.4.33.Final

/**
 * PorcentajesRangoedad generated by hbm2java
 */
public class PorcentajesRangoedad implements java.io.Serializable {

	private String nombrePais;
	private int rango19;
	private int rango1017;
	private int rango1825;
	private int rango2640;
	private int rango4165;
	private int rangoMas66;
	private int totalHabitantes;

	public PorcentajesRangoedad() {
	}

	public PorcentajesRangoedad(String nombrePais, int rango19, int rango1017, int rango1825, int rango2640,
			int rango4165, int rangoMas66, int totalHabitantes) {
		this.nombrePais = nombrePais;
		this.rango19 = rango19;
		this.rango1017 = rango1017;
		this.rango1825 = rango1825;
		this.rango2640 = rango2640;
		this.rango4165 = rango4165;
		this.rangoMas66 = rangoMas66;
		this.totalHabitantes = totalHabitantes;
	}

	public String getNombrePais() {
		return this.nombrePais;
	}

	public void setNombrePais(String nombrePais) {
		this.nombrePais = nombrePais;
	}

	public int getRango19() {
		return this.rango19;
	}

	public void setRango19(int rango19) {
		this.rango19 = rango19;
	}

	public int getRango1017() {
		return this.rango1017;
	}

	public void setRango1017(int rango1017) {
		this.rango1017 = rango1017;
	}

	public int getRango1825() {
		return this.rango1825;
	}

	public void setRango1825(int rango1825) {
		this.rango1825 = rango1825;
	}

	public int getRango2640() {
		return this.rango2640;
	}

	public void setRango2640(int rango2640) {
		this.rango2640 = rango2640;
	}

	public int getRango4165() {
		return this.rango4165;
	}

	public void setRango4165(int rango4165) {
		this.rango4165 = rango4165;
	}

	public int getRangoMas66() {
		return this.rangoMas66;
	}

	public void setRangoMas66(int rangoMas66) {
		this.rangoMas66 = rangoMas66;
	}

	public int getTotalHabitantes() {
		return this.totalHabitantes;
	}

	public void setTotalHabitantes(int totalHabitantes) {
		this.totalHabitantes = totalHabitantes;
	}

	@Override
	public String toString() {
		return "PorcentajesRangoedad [nombrePais=" + nombrePais + ", rango19=" + rango19 + ", rango1017=" + rango1017
				+ ", rango1825=" + rango1825 + ", rango2640=" + rango2640 + ", rango4165=" + rango4165 + ", rangoMas66="
				+ rangoMas66 + ", totalHabitantes=" + totalHabitantes + "]";
	}

}
